// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vatsal278/AccountManagmentSvc/internal/handler (interfaces: AccountManagmentSvcHandler)

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountManagmentSvcHandler is a mock of AccountManagmentSvcHandler interface.
type MockAccountManagmentSvcHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAccountManagmentSvcHandlerMockRecorder
}

// MockAccountManagmentSvcHandlerMockRecorder is the mock recorder for MockAccountManagmentSvcHandler.
type MockAccountManagmentSvcHandlerMockRecorder struct {
	mock *MockAccountManagmentSvcHandler
}

// NewMockAccountManagmentSvcHandler creates a new mock instance.
func NewMockAccountManagmentSvcHandler(ctrl *gomock.Controller) *MockAccountManagmentSvcHandler {
	mock := &MockAccountManagmentSvcHandler{ctrl: ctrl}
	mock.recorder = &MockAccountManagmentSvcHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountManagmentSvcHandler) EXPECT() *MockAccountManagmentSvcHandlerMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockAccountManagmentSvcHandler) HealthCheck() (string, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockAccountManagmentSvcHandlerMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockAccountManagmentSvcHandler)(nil).HealthCheck))
}

// Ping mocks base method.
func (m *MockAccountManagmentSvcHandler) Ping(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ping", arg0, arg1)
}

// Ping indicates an expected call of Ping.
func (mr *MockAccountManagmentSvcHandlerMockRecorder) Ping(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAccountManagmentSvcHandler)(nil).Ping), arg0, arg1)
}
